name: voicerra
description: Voicerra - Audio Revolution.
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: ">=2.17.6"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  speech_to_text: ^5.6.1
  highlight_text: ^1.4.0
  flutter_speed_dial: ^6.0.0
  clipboard: ^0.1.3
  sqflite: ^2.0.3+1
  share: ^2.0.1
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  iconsax: ^0.0.8
  google_speech: ^2.0.1
  permission_handler: ^10.0.0
  loading_indicator: ^3.0.1
  line_icons: ^2.0.1
  package_info_plus: ^1.4.3+1
  url_launcher: ^6.1.5
  flex_color_scheme: ^6.0.1
  fluttertoast: ^8.0.9
  flutter_sound: ^9.1.2
  sliding_sheet: ^0.5.2
  stop_watch_timer: ^1.3.1
  path_provider: ^2.0.8
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  share_plus: ^4.1.0
  wakelock: ^0.6.1+1
  auto_size_text: ^3.0.0
  flutter_vibrate: ^1.3.0
  google_fonts: ^3.0.1
  file_picker: ^5.0.1
  translator: ^0.1.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #assets:
   # - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Light.ttf


    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf


  assets:
    - assets/images/
    - assets/cloud.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
